module.exports = Object.freeze({
  COMMENTS: [
    "Đẹp quá",
    "Đẹp quá",
    "Giản dị, đẹp và đầy ý nghĩa.",
    "Đẹp quá béo ah",
    "đẹp .ý nghĩa",
    "Ý nghĩa vô cùng",
    "😍😍😍",
    "Đẹp thật",
    "Wow chữ đẹp tranh có ý nghĩa cảm động quá",
    "Đẹp qua!",
    "Bài thơ rất xúc động và ý nghĩa. Cảm động quá! Xứng đáng giải nhất",
    "Quá đẹp",
    "Đẹp thật sự 10đ",
    "Bức tranh trong trẻo như tâm hồn trẻ thơ của các con. Nhìn tranh lại nhớ tuổi thơ làm báo tường nhân ngày nhà giáo Việt Nam của bao thế hệ",
    "Hay và ý nghĩa.",
    "Đẹp vô cùng",
    "Đẹp quá",
    "Bức tranh đẹp vô cùng, bài thơ hay và ý nghĩa thật sâu sắc",
    "😍😍Bạn viết đẹp quá",
    "F",
    "😘😍😮😮",
    "Nét vẽ đẹp vô cùng bài thơ thật ý nghĩa",
    "😍",
    "Ấn tượng thật",
    "Đẹp quá",
    "Đẹp quá em ei",
    "eo ôi nhìn có hồn thực sự luôn ý",
    "Bạn này giỏi quá",
    "10 điểm",
    "Bé giỏi quá 😻",
    "quá xúc xắc",
    "Nét vẽ mộc mạc giản dị thể hiện sự trong sáng của trẻ thơ đi cùng với bài thơ đầy ý nghĩa và cảm động làm người đọc ấn tượng",
    "😮😮😮😮😮😮Bạn ấy viết đẹp quá",
    "Thật xúc động",
    "Bạn ấy giỏi quá",
    "Bức trânh cùng bài thơ thật tuyệt vời",
    "Chữ viết của bạn đẹp bức tranh giản dị.10 điểm",
    "Tranh đẹp, thơ hay thơ và hoạ hoà quyện vào nhau giản dị mà chân thành. Tình cảm thật từ đáy lòng con trẻ kính dâng lên thầy cô nhiều cảm xúc và thật ý nghĩa.",
    "Đẹp quá",
    "Đẹp quá đi à giỏi thật đấy",
    "Ngôn từ mộc mạc chân thành cùng với sự kết hợp của thể thơ lục bát và tấm lòng thành kính biết ơn của con trẻ đã làm nên một bài thơ đáng được trân trọng",
    "ĐẸP quá điii",
    "Thật là một bức thư gửi thầy cô ý nghĩa và sâu sắc biết bao",
    "Công nhận bức thư của bạn Ngọc An đẹp thật",
    "em viết đẹp cá",
    "Thật đẹp luôn á",
    "Đẹp thật sự",
    "Bức tranh day ý nghĩa và Dep quá",
    "Bức thư tràn đầy ý nghĩa sau sắc",
    "An vẽ đẹp, lời thơ giản dị, mộc mạc và gần gũi!",
    "Xinh đẹp quá ❤",
    "Em bé khéo tay quá",
    "Bạn ấy khéo tay quá vẽ đẹp lại còn thơ hay nữa thật khâm phục",
    "Khéo tay quá",
    "Đẹp quá",
    "😍😍😍",
    "Thật là ý nghĩa",
    "Ôi đẹp quá đi",
    "dep thuc su, toi khong dua",
    "Đẹp quá",
    "Đẹp quá",
    "Giản dị, đẹp và đầy ý nghĩa.",
    "Đẹp quá béo ah",
    "đẹp .ý nghĩa",
    "Ý nghĩa vô cùng",
    "😍😍😍",
    "Đẹp thật",
    "Wow chữ đẹp tranh có ý nghĩa cảm động quá",
    "Đẹp qua!",
    "Bài thơ rất xúc động và ý nghĩa. Cảm động quá! Xứng đáng giải nhất",
    "Quá đẹp",
    "Đẹp thật sự 10đ",
    "Bức tranh trong trẻo như tâm hồn trẻ thơ của các con. Nhìn tranh lại nhớ tuổi thơ làm báo tường nhân ngày nhà giáo Việt Nam của bao thế hệ",
    "Hay và ý nghĩa.",
    "Đẹp vô cùng",
    "Đẹp quá",
    "Bức tranh đẹp vô cùng, bài thơ hay và ý nghĩa thật sâu sắc",
    "😍😍Bạn viết đẹp quá",
    "F",
    "😘😍😮😮",
    "Nét vẽ đẹp vô cùng bài thơ thật ý nghĩa",
    "😍",
    "Ấn tượng thật",
    "Đẹp quá",
    "Đẹp quá em ei",
    "eo ôi nhìn có hồn thực sự luôn ý",
    "Bạn này giỏi quá",
    "10 điểm",
    "Bé giỏi quá 😻",
    "quá xúc xắc",
    "Nét vẽ mộc mạc giản dị thể hiện sự trong sáng của trẻ thơ đi cùng với bài thơ đầy ý nghĩa và cảm động làm người đọc ấn tượng",
    "😮😮😮😮😮😮Bạn ấy viết đẹp quá",
    "Thật xúc động",
    "Bạn ấy giỏi quá",
    "Bức trânh cùng bài thơ thật tuyệt vời",
    "Chữ viết của bạn đẹp bức tranh giản dị.10 điểm",
    "Tranh đẹp, thơ hay thơ và hoạ hoà quyện vào nhau giản dị mà chân thành. Tình cảm thật từ đáy lòng con trẻ kính dâng lên thầy cô nhiều cảm xúc và thật ý nghĩa.",
    "Đẹp quá",
    "Đẹp quá đi à giỏi thật đấy",
    "Ngôn từ mộc mạc chân thành cùng với sự kết hợp của thể thơ lục bát và tấm lòng thành kính biết ơn của con trẻ đã làm nên một bài thơ đáng được trân trọng",
    "ĐẸP quá điii",
    "Thật là một bức thư gửi thầy cô ý nghĩa và sâu sắc biết bao",
    "Công nhận bức thư của bạn Ngọc An đẹp thật",
    "em viết đẹp cá",
    "Thật đẹp luôn á",
    "Đẹp thật sự",
    "Bức tranh day ý nghĩa và Dep quá",
    "Bức thư tràn đầy ý nghĩa sau sắc",
    "An vẽ đẹp, lời thơ giản dị, mộc mạc và gần gũi!",
    "Xinh đẹp quá ❤",
    "Em bé khéo tay quá",
    "Bạn ấy khéo tay quá vẽ đẹp lại còn thơ hay nữa thật khâm phục",
    "Khéo tay quá",
    "Đẹp quá",
    "😍😍😍",
    "Thật là ý nghĩa",
    "Ôi đẹp quá đi",
    "dep thuc su, toi khong dua"
  ]
})