module.exports = Object.freeze({
  COMMENTS: [
    "Đẹp quá",
    "Đẹp quá",
    "Giản dị, đẹp và đầy ý nghĩa.",
    "Đẹp quá béo ah",
    "đẹp .ý nghĩa",
    "Ý nghĩa vô cùng",
    "😍😍😍",
    "Đẹp thật",
    "Wow chữ đẹp tranh có ý nghĩa cảm động quá",
    "Đẹp qua!",
    "Bài thơ rất xúc động và ý nghĩa. Cảm động quá! Xứng đáng giải nhất",
    "Quá đẹp",
    "Đẹp thật sự 10đ",
    "Bức tranh trong trẻo như tâm hồn trẻ thơ của các con. Nhìn tranh lại nhớ tuổi thơ làm báo tường nhân ngày nhà giáo Việt Nam của bao thế hệ",
    "Hay và ý nghĩa.",
    "Đẹp vô cùng",
    "Đẹp quá",
    "Bức tranh đẹp vô cùng, bài thơ hay và ý nghĩa thật sâu sắc",
    "😍😍Bạn viết đẹp quá",
    "F",
    "😘😍😮😮",
    "Nét vẽ đẹp vô cùng bài thơ thật ý nghĩa",
    "😍",
    "Ấn tượng thật",
    "Đẹp quá",
    "Đẹp quá em ei",
    "eo ôi nhìn có hồn thực sự luôn ý",
    "Bạn này giỏi quá",
    "10 điểm",
    "Bé giỏi quá 😻",
    "quá xúc xắc",
    "Nét vẽ mộc mạc giản dị thể hiện sự trong sáng của trẻ thơ đi cùng với bài thơ đầy ý nghĩa và cảm động làm người đọc ấn tượng",
    "😮😮😮😮😮😮Bạn ấy viết đẹp quá",
    "Thật xúc động",
    "Bạn ấy giỏi quá",
    "Bức trânh cùng bài thơ thật tuyệt vời",
    "Chữ viết của bạn đẹp bức tranh giản dị.10 điểm",
    "Tranh đẹp, thơ hay thơ và hoạ hoà quyện vào nhau giản dị mà chân thành. Tình cảm thật từ đáy lòng con trẻ kính dâng lên thầy cô nhiều cảm xúc và thật ý nghĩa.",
    "Đẹp quá",
    "Đẹp quá đi à giỏi thật đấy",
    "Ngôn từ mộc mạc chân thành cùng với sự kết hợp của thể thơ và tấm lòng thành kính biết ơn của con trẻ đã làm nên một bài thơ đáng được trân trọng",
    "ĐẸP quá điii",
    "Thật là một bức thư gửi thầy cô ý nghĩa và sâu sắc biết bao",
    "Công nhận bức thư của bạn đẹp thật",
    "em viết đẹp cá",
    "Thật đẹp luôn á",
    "Đẹp thật sự",
    "Bức tranh day ý nghĩa và Dep quá",
    "Bức thư tràn đầy ý nghĩa sau sắc",
    "An vẽ đẹp, lời thơ giản dị, mộc mạc và gần gũi!",
    "Xinh đẹp quá ❤",
    "Em bé khéo tay quá",
    "Bạn ấy khéo tay quá vẽ đẹp lại còn thơ hay nữa thật khâm phục",
    "Khéo tay quá",
    "Đẹp quá",
    "😍😍😍",
    "Thật là ý nghĩa",
    "Ôi đẹp quá đi",
    "dep thuc su, toi khong dua",
    "Con vẽ đẹp, viết đẹp, thật là giỏi!",
    "Bài của con thật hay và ý nghĩa, hoa vẽ rất đẹp!",
    "Thực sự đẹp và ý nghĩa, chúc mừng TQ",
    "Con vẽ đẹp quá",
    "Đẹp quá",
    "Thực sự ý nghĩa",
    "Đẹp quá",
    "Đẹp nhé",
    "Great job",
    "Tranh vẽ rất đẹp, bài viết ý nghĩa",
    "Chúc con đạt giải nhé!",
    "nhéé",
    "Đẹp quá",
    "chúc mừng",
    "chúc mừng con",
    "đẹp đẹpp!đđ!đđ",
    "con bố vẽ đẹp quá !",
    "hay quá TQ",
    "đẹp con nhé!",
    "Khéo tay quá con!",
    "tuyệt",
    "tuyệt vời",
    "tranh vẽ đẹp",
    "tranh vẽ đẹp quá",
    "vẽ đẹp đó!",
    "Tuyệt",
    "Đẹp quá",
    "tranh ve dep va y nghia con nhe",
    "con bố vẽ đẹp quá",
    "Wow đẹp quá ♥️♥️",
    "10đ cho TQ",
    "Khéo tay quá con!",
    "Wow chữ đẹp tranh có ý nghĩa cảm động quá",
    "Đẹp quá,chúc mừng con gái nhé.",
    "đẹp lắm TQ ♥️♥️♥️♥️♥️♥️♥️♥️",
    "Chúc con gái sẽ đạt giải nhé !",
    "học trường mới à, chúc con gái học tốt nhé, con gái vẽ đẹp quá",
    "Cháu gái vẽ đẹp, lời văn cảm xúc, hy vọng bức tranh đat giải",
    "Bé giỏi quá 😻",
    "lâu ko gặp TQ, con gái vẫn vẽ đẹp như ngày xưa !",
    "Hay và ý nghĩa.",
    "con gái bố mẹ vẽ đẹp quá!",
    "Hoa đẹp, chữ đẹp, lời văn cảm xúc, chúc mừng con !",
    "Bài viết đọc cô thấy cảm động TQ à!",
    "Đẹp nhé",
    "Bức thư tràn đầy ý nghĩa và màu sắc",
    "Chúc con đạt giải nhé!",
    "tranh vẽ đẹp quá chữ viết cũng đẹp🥰",
    "đẹp con à, hôm nào vẽ tặng e Linh 1 bức nhé!",
    "Tuyêt vời nhé !",
    "nét viền đẹp, chúc con sẽ đạt giải !",
    "Nét vẽ mộc mạc giản dị thể hiện sự trong sáng của trẻ thơ đi cùng với bài thơ đầy ý nghĩa và cảm động làm người đọc ấn tượng",
    "đẹp lắm TQ ♥️♥️♥️♥️♥️♥️♥️♥️",
    "ok, đẹp đó con, chúc con đạt giải !",
    "Một tác phẩm đầy ý nghĩa và nhân văn sâu sắc!",
    "Cháu gái của bác vẽ đẹp quá !",
    "Chúc con đạt giải !",
    "rất tuyệt vời, cô cũng ko vẽ được hoa như thế này, giỏi quá con",
    "Chúc con gái sẽ đạt giải nhé !",
    "đẹp quá Heo ơi, chúc con đạt giải !",
    "wow wow wow !!! đẹp.......",
    "Bài của con thật hay và ý nghĩa, hoa vẽ rất đẹp!",
    "good job con gái !",
    "Bức tranh ý nghĩa quá !",
    "Bài viết đọc cô thấy cảm động quá đi",
    "tuyệt vời",
    "Đẹp thật sự",
    "Đẹp nhé",
    "Khéo tay quá con!",
    "đẹp .ý nghĩa",
    "nice",
    "Chúc con gái sẽ đạt giải nhé !",
    "Bức tranh đẹp vô cùng, bài viết hay và ý nghĩa thật sâu sắc",
    "Tuyệt vời Heo ơi !",
    "con gái vẽ hoa đẹp qúa, bác chúc con đạt giải nhé !",
    "Chúc con đạt giải nhé !",
    "Great con gái ơi !",
    "Con vẽ đẹp quá",
    "Thật là một bức thư gửi thầy cô ý nghĩa và sâu sắc biết bao",
    "Đẹp nhé",
    "đẹp quá 😍😍😍",
    "Con vẽ khéo lắm",
    "con vẽ đẹp, chúc con đạt giải !",
    "Đẹp nhé",
    "Con xứng đáng được giải nhất",
    "Bài viết thật sự ý nghĩa. Con vẽ đẹp quá",
    "Tuyệt vời, trên cả tuyệt vời TQ nhé !",
    "Tranh vẽ đẹp, lời văn cảm xúc, chúc con đạt giải nhé !",
    "Chúc đạt giải cao nhé!",
    "woww, tuyệt con gái !",
    "Thực sự đẹp và ý nghĩa, chúc mừng TQ",
    "đẹp và ý nghĩa",
    "Chúc cho TQ đạt giải cao nhé ! Tranh con vẽ rất đẹp !",
    "Đúng là con bố có khác !",
    "ok, đẹp, chúc con đạt giải !",
    "Tuyệt vời !",
    "Chúc con đạt giải nhé !",
    "Khéo tay quá con!",
    "đẹp, chúc cháu gái đạt giải nhé !",
    "lời văn cảm xúc, chúc con đạt giải nhé !",
    "Con vẽ đẹp quá🥰",
    "e cảm ơn ah.",
    "Đẹp lắm ơi",
    "Chữ đẹp quá.",
    "Trà vẽ đẹp quá",
    "Con vẽ rất đẹp, bố cục tranh nhìn thoáng,",
    "Đẹp quá con ơi",
    "vẽ giỏi thế",
    "Chữ người lái đò rất là nghệ thuật",
    "Đẹp quá 🤩",
    "Trên cả Tuyệt vờii",
    "Rất đẹp và ý nghĩa ❤️",
    "Bài viết đẹp và tư nghĩa!",
    "👍",
    "con giỏi quá",
    "Con vẽ đẹp ,nội dung hay.Chúc mừng con nhé.",
    "👍👍👍",
    "Chúc con đạt giải cao nha",
    "đẹp quá",
    "Chữ viết đẹp, bố cục tranh hợp lý. Bức tranh ý nghĩa.Chúc mừng con!",
    "Con mẹ đạt giải nhé",
    "👍😘",
    "Đây rui.",
    "Bạn í giỏi quá",
    "Chúc con luôn hiểu ý nghĩa bài con vừa viết dự thi nhé!",
    "ý nghĩa quá",
    ":3 Bé con vẽ đẹp quá",
    "From KMA with love, chữ bé đẹp quáaa",
    "From KMA with love",
    "Con vẽ đẹp quá",
    "From KMA with love.",
    "Bé con vẽ đẹp ghê. Rất chỉn chu trong bài làm",
    "Quá tuyệt vời",
    "From KMA <3",
    "from KMA with luv",
    "Bé vẽ đẹp quá <3",
    "Đẹp quá ạ",
    "From KMA with love",
    "đẹp quá.. km4 w1th l0v3",
    "Con vẽ đẹp quá, chúc con đạt giải nhé",
    "From KMA with love <3",
    "From KMA with love . Chúc bé đạt giải cao",
    "From KMA. Chúc bé đạt giải nhé❤❤",
    "pro quá >))",
    "KMA w<3 love",
    "vẽ tranh đẹp lắm",
    "Chúc bé đạt giải và điểm cao nhé",
    "Vẽ đẹp quá from KMA with love",
    "vip quá",
    "Bài con hay quá",
    "Giỏi quá :))",
    "bài thơ hay quá",
    "Bức ảnh waa xinh. Mong em đạt giải 🥳🥳 from KMA",
    "From KMA with love",
    "Hay quá ạ, chúc bé đạt giải nhé from KMA ❤💕💕🤞",
    "KMA with love",
    "Thơ hay quá",
    "Trà vẽ đẹp quá♥️",
    "from KMA with love",
    "From KMA with love",
    "Chữ con đẹp quá ❤️",
    "Chuẩn con mẹ rồi ạ",
    "Chữ con đepj quá",
    "Tuyệt vời",
    "vẽ đẹp, chữ đẹp, hình ảnh và bài đều rất ý nghĩa. Chúc con đạt giải cao nhé ❤️🌼",
    "Con vẽ và viết đẹp quá",
    "Chúc con mẹ đạt giải nhé, vẽ đẹp quá",
    "Tuyệt quá. Rất chuẩn con mẹ",
    "Con trang trí đẹp quá!",
    "Bài thơ rất ý nghĩa!!!",
    "Chúc con bố đạt giải cao nhé🥰🥰♥️♥️",
    "Đẹp quá",
    "Hay quá",
    "Vẽ rất đẹp",
    "Con vẽ đẹp quá",
    "Đẹp quá"
  ]
})